version: '3.8'

services:
  server:
    env_file:
      - '.env.development'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - backend-composter-gems-sync:/usr/local/bundle/
    container_name: backend_composter_server
    depends_on:
      - postgres-db

  postgres-db:
    restart: always
    image: postgres
    volumes:
      - backend-composter-postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    container_name: backend_composter_db

volumes:
  backend-composter-gems-sync:
  backend-composter-postgres:
