default: &default
  adapter: <%= ENV.fetch('DATABASE_ADAPTER', 'postgresql' ) %>
  encoding: <%= ENV.fetch('DATABASE_ENCODING', 'unicode' ) %>
  pool: <%= ENV.fetch('DATABASE_POOL', 5) %>
  username: <%= ENV.fetch('POSTGRES_USER', 'postgres') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', 'postgres') %>
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  timeout: <%= ENV.fetch('DATABASE_TIMEOUT', 5000) %>

development:
  database: <%= ENV['DATABASE_NAME'] %>_development
  <<: *default

test:
  database: <%= ENV['DATABASE_NAME'] %>_test
  <<: *default

production:
  database: <%= ENV['DATABASE_NAME'] %>
  <<: *default
